### ISSUE TITLE
InvalidOperationException in Hebrew Calendar 9.28

### ISSUE THREAD

**Issue by jklein001** [Ordisoftware/Hebrew-Calendar#1159]
## COMMENT

> Describe here what you did, what you expected and what happened.

## SYSTEM

```
Windows 10 Home 21H2 64-bits v6.3.22000
.NET Framework 4.8
CLR 4.0.30319.42000
Total Memory: 15.78 GiB
Free Memory: 7.78 GiB
```

## ERROR : InvalidOperationException

Nullable object must have a value.

#### _STACK_

```
---------- EXCEPTION STACK ----------

MainForm.Reminder.CelebrationDay.cs line 36:
Ordisoftware.Hebrew.Calendar.MainForm.CheckCelebrationDay

MainForm.Reminder.Timers.cs line 62:
Ordisoftware.Hebrew.Calendar.MainForm.DoTimerReminder

---------- THREAD STACK -------------

MainForm.Reminder.Timers.cs line 62:
Ordisoftware.Hebrew.Calendar.MainForm.DoTimerReminder

MainForm.Initialize.cs line 158:
Ordisoftware.Hebrew.Calendar.MainForm.DoFormShown

Program.cs line 72:
Ordisoftware.Hebrew.Calendar.Program.Main
```

## LOG

```

```

**Comment by Ordisoftware** [comment]
Dear,

I don't understand why the stack shows line 36 which is a return, possibly a compiler optimization of the double line test for readability. The error seems to occur in the unmentioned GetTimesForCelebration method called in the next line. In this case, why this happens depends on values ​​shouldn't be null or I must have missed something in the logic.

I know that for lack of time I have sometimes skipped a lot of things and that some bits of code are not very clean, especially null checks and some condition tests, which normally is not an excuse, but in a hurry I hope that the code, even sometimes draft, is well enough thought out to be easily maintainable. Anyway...

The generation parameters are necessary to try to reproduce and have a certainty: first year, last year, moon or sun omer, day of the shabat, simchat inside or outside, and especially the GPS coordinates but do not post GPS here, but by email, twitter or linkedin msg.

For the time being, I've added checks and you may be able to verify with the next v9.29 if this happens again (for the celebration and system dates the exception occurred): https://github.com/Ordisoftware/Hebrew-Calendar/commit/5642c4fe10ac4bb37d31f6309760c19c47800d00

Thank you for helping the software to improve 😀
