### ISSUE TITLE
Error on first launch for Parashot table

### ISSUE THREAD

**Issue by raelb** [Ordisoftware/Hebrew-Calendar#1287]
Hi,
I'm trying to run from source (using latest source, and vs2022), and get following errors when trying to run:

![image](https://user-images.githubusercontent.com/13108198/222723110-5068ce57-e7c8-4dda-89bb-c04f18d19360.png)

![image](https://user-images.githubusercontent.com/13108198/222723221-8e3e44fa-1655-493b-aa10-23ac4eea8353.png)

![image](https://user-images.githubusercontent.com/13108198/222723383-00413742-3a25-4c51-94c2-e296ca13d4ee.png)

**Comment by Ordisoftware** [comment]
Dear,
Indeed, it lacks a check if the table exists in the HebrewDatabase.cs recent changes for the UpgradeSchema method.
It has been fixed and the repository has been updated.
A new version 10.3 is available.
Thank you!
Best regards,
Olivier

![image](https://user-images.githubusercontent.com/22332878/222730585-02ecfc0e-f671-496e-b012-2a13f5f97c98.png)
